[versions]
agp = "8.1.0"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
glide = "4.13.2"
gson = "2.10.1"
kotlin = "1.9.0"
mdc = "1.9.0"
multidex = "2.0.1"
recyclerview = "1.3.1"
retrofit = "2.9.0"
rxandroid = "2.1.1"
rxjava = "2.2.21"

[libraries]
androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx_constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx_multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx_recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
mdc = { module = "com.google.android.material:material", version.ref = "mdc" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit_gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }


[plugins]
versions = { id = "com.android.application", version.ref = "agp" }
